#!/usr/bin/env bash
#
# DESCRIPTION
#   Sort strings alphabetically.
#   The string to alphabetize is retrieved from the Clipboard.
#
# USAGE
#   abc [OPTIONS]
#
# ARGUMENTS
#   None
#
# OPTIONS
#   -h, --help    Show this help message
#
# EXAMPLES
#   None

# Print usage information.
function usage() {
  echo "usage: $0 [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help    Show this help message"
  echo ""
}

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if ! [ -x "$(command -v pbcopy)"  ]; then
  echo 'Error: pbcopy is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v pbpaste)"  ]; then
  echo 'Error: pbpaste is not installed.' >&2
  exit 1
fi

pbpaste | sort | pbcopy
