#!/usr/bin/env bash
#
# DESCRIPTION
#   Sort strings alphabetically.
#   The strings to alphabetize is retrieved from the Clipboard.
#
# USAGE
#   abc [OPTIONS]
#
# ARGUMENTS
#   None
#
# OPTIONS
#   -h, --help    Show this help message
#
# EXAMPLES
#   None

# Colors
red='\033[0;31m'
reset='\033[0m'

# Print usage information.
function usage() {
  echo "usage: abc [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help    Show this help message"
  echo ""
}

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if ! [ -x "$(command -v pbcopy)" ]; then
  echo -e "${red}ERROR: pbcopy is not installed.${reset}" >&2
  exit 1
fi

if ! [ -x "$(command -v pbpaste)" ]; then
  echo -e "${red}ERROR: pbpaste is not installed.${reset}" >&2
  exit 1
fi

pbpaste | sort | pbcopy
