#!/usr/bin/env bash
#
# DESCRIPTION
#   Print system info to the console.
#
# USAGE
#   apple [OPTIONS]
#
# ARGUMENTS
#   None
#
# OPTIONS
#   -c, --color    Whether to colorize output
#   -h, --help     Show this help message
#
# EXAMPLES
#   None

# Print usage information.
function usage() {
  echo "usage: $0 [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -c, --color    Whether to colorize output"
  echo "  -h, --help     Show this help message"
  echo ""
}

color=false

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -c|--color) color=true; shift ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

# Colors
if [ "${color}" == "true" ]; then
  red='\033[0;31m'
  orange='\033[1;31m'
  green='\033[0;32m'
  yellow='\033[0;33m'
  blue='\033[0;34m'
  purple='\033[0;35m'
  reset='\033[0m'
fi

user=$(whoami)
hostname=$(hostname | sed 's/.local//g')

version="OS X $(sw_vers -productVersion)"
version_number=$(sw_vers -productVersion)
version_major=$(echo "${version_number}" | cut -d'.' -f1)
version_minor=$(echo "${version_number}" | cut -d'.' -f2)
version_short="${version_major}.${version_minor}"

case "${version_short}" in
  11.6)
    version_string="Big Sur"
    ;;
  10.15)
    version_string="Catalina"
    ;;
  10.14)
    version_string="Mojave"
    ;;
  10.13)
    version_string="High Sierra"
    ;;
  10.12)
    version_string="Sierra"
    ;;
  10.11)
    version_string="El Capitan"
    ;;
  10.10)
    version_string="Yosemite"
    ;;
  10.9)
    version_string="Mavericks"
    ;;
  10.8)
    version_string="Mountain Lion"
    ;;
  10.7)
    version_string="Lion"
    ;;
  10.6)
    version_string="Snow Leopard"
    ;;
  10.5)
    version_string="Leopard"
    ;;
  10.4)
    version_string="Tiger"
    ;;
  10.3)
    version_string="Panther"
    ;;
  10.2)
    version_string="Jaguar"
    ;;
  10.1)
    version_string="Puma"
    ;;
  10.0)
    version_string="Cheetah"
    ;;
esac

int_ip_addr=$(ipconfig getifaddr en1)

if [ -z "${int_ip_addr}" ]; then
  int_ip_addr=$(ipconfig getifaddr en0)
fi

ext_ip_addr=$(curl -s -m 1 ifconfig.me)

kernel=$(uname)
uptime=$(uptime | sed 's/.*up \([^,]*\), .*/\1/')
shell="${SHELL}"
terminal="${TERM}"
packages="$(brew list -l --formulae | wc -l | awk '{print $1}')"
cpu=$(sysctl -n machdep.cpu.brand_string)
mem=$(sysctl -n hw.memsize)
ram="$((mem/1073741824)) GB"
disk=$(df | head -2 | tail -1 | awk '{print $5}')

echo -en "
${green}                              .8
${green}                            .888
${green}                          .8888'
${green}                         .8888'
${green}                         888'
${green}                         8'
${yellow}            .88888888888. .88888888888.
${yellow}         .888888888888888888888888888888.         User: ${user}
${yellow}       .8888888888888888888888888888888888.       Hostname: ${hostname}
${orange}      .&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'         Version: ${version} ${version_string}
${orange}      &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'           Kernel: ${kernel}
${orange}      &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&'            Uptime: ${uptime}
${red}      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.            Shell: ${shell}
${red}      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.           Terminal: ${terminal}
${red}      \`%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.         Packages: ${packages}
${purple}       \`0000000000000000000000000000000000'       CPU: ${cpu}
${purple}        \`00000000000000000000000000000000'        Memory: ${ram}
${purple}          \`############################'          Disk Used: ${disk}
${blue}            \`########################'            Internal IP: ${int_ip_addr}
${blue}              \`#########''#########'              External IP: ${ext_ip_addr}
${blue}                \`\"\"\"\"\"\"'  \`\"\"\"\"\"\"'
${reset}
"

tput sgr0
