#!/bin/bash
#
# DESCRIPTION
# Retrieve AWS SAML credentials from credential broker.
#
# USAGE
#
#   aws-credentials <profile>
#
# ADDITIONAL INFORMATION
#
# Executing JavaScript through AppleScript must be turned on. To turn it on,
# from the menu bar, go to View > Developer > Allow JavaScript from Apple
# Events.
#
# For more information, see:
#   * https://support.google.com/chrome/?p=applescript
#
# NOTE: This script is specific to Workiva.

function usage {
  echo 'usage: aws-credentials <profile>'
  echo ''
  echo '  Arguments:'
  echo '    profile: Named profile for the AWS CLI'
  echo '      * A named profile is a collection of settings and credentials'
  echo '        that you can apply to a AWS CLI command.'
  echo '        See (~/.aws/config).'
}

if [ -z "${1}" ]; then
  echo -en "\033[0;31m"
  echo "ERROR: Must specify a profile."
  echo -en "\033[0m"
  usage
  exit 1
fi

case "${1}" in
  'workiva.corp')
    url="https://aws-saml-broker-corp.workiva.net"
    ;;
  'workiva.prod')
    url="https://aws-saml-broker.workiva.net"
    ;;
  'workiva.dev')
    url="https://aws-saml-broker-dev.workiva.net"
    ;;
  *)
    echo -en "\033[0;31m"
    echo "ERROR: 'profile' must be one of:"
    echo "  * workiva.corp"
    echo "  * workiva.prod"
    echo "  * workiva.dev"
    echo -en "\033[0m"
    exit 1
    ;;
esac

content=$(osascript <<EOD
set current_application to path to frontmost application as text
tell application "Google Chrome"
	if not running then
		launch
		delay 5
	end if
	open location "${url}"
repeat while loading of active tab of window 1
	delay 1
end repeat
set content to execute active tab of window 1 javascript "document.documentElement.innerText"
	tell active tab of window 1 to close
end tell
tell application "System Events"
  set visible of process "Google Chrome" to false
end tell
activate application current_application
return content
EOD
)

credentials=$(tail -n 4 <<< "${content}")
gsed -i "/${1}/,+4d" "${HOME}/.aws/credentials"
cat <<EOT >> "${HOME}/.aws/credentials"

[${1}]
${credentials}
EOT
gsed -i 's/\\$//;/./,/^$/!d' "${HOME}/.aws/credentials"
