#!/bin/bash
#
# DESCRIPTION
# Set user.name and user.email for each repository in the current directory.
#
# USAGE
#
#   git-config-all [user.name] [user.email]
#
# EXAMPLE
#
#   git-config-all 'Nickolas Kraus' 'NickolasKraus@granular.ag'

function usage {
  echo 'usage: git-config-all [user.name] [user.email]'
  echo ''
  echo '  Arguments:'
  echo '    user.name: User name'
  echo '    user.email: User email'
}

if [ -z "${1}" ]; then
  echo -en "\033[0;31m"
  echo "Specify a user name."
  echo -en "\033[0m"
  usage
  exit 1
fi

if [ -z "${2}" ]; then
  echo -en "\033[0;31m"
  echo "Specify a user email."
  echo -en "\033[0m"
  usage
  exit 1
fi

user_name="${1}"
user_email="${2}"

for d in *; do \
  if [ -d "${d}" ]; then
    pushd "${d}" >/dev/null || exit
    git config user.name "${user_name}" && \
    git config user.email "${user_email}"
    popd >/dev/null || exit
  fi
done
