#!/usr/bin/env bash
#
# DESCRIPTION
#   Show remotes for all Git repositories for a given directory.
#
# USAGE
#   git-remote-v [DIR]
#
# ARGUMENTS
#   DIR    Directory to use (optional, defaults to current directory)
#
# OPTIONS
#   None
#
# EXAMPLES
#   None

# Print usage information
function usage {
  echo "usage: $0 [DIR]"
  echo ""
  echo "Arguments:"
  echo "  DIR    Directory to use (optional, defaults to current directory)"
}

dir="${1}"

if [ -z "${dir}" ]; then
  dir="$(pwd)"
else
  if [ ! -e "${dir}" ]; then
    echo -en "\033[0;31m"
    echo "${dir} does not exist."
    echo -en "\033[0m\n"
    exit 1
  fi
fi

for d in "${dir}"/*; do

  [ -d "${d}" ] || continue

  basename "${d}"

  if [ ! -d "${d}/.git" ]; then
    echo -en "\033[0;31m"
    echo "$(basename "${d}") is not a Git repository."
    echo -en "\033[0m"
    continue
  fi

  pushd "${d}" >/dev/null || exit

  echo -en "\033[0;32m" # display green
  git remote -v
  echo -en "\033[0m"

  popd >/dev/null || exit

done
