#!/bin/bash
#
# DESCRIPTION
# Clone all GitHub repositories for the specified user or organization.
#
# USAGE
#
#   git-clone-gh [-u, --user user] [-o, --org org] [-i identity_file] [access-token]
#
# EXAMPLE
#
#   git-clone-gh -u NickolasHKraus
#
#   git-clone-gh -o Workiva
#
# ADDITIONAL INFORMATION
#
# GitHub recommends you use OAuth tokens to authenticate to the GitHub API.
# OAuth tokens include personal access tokens and enable the user to revoke
# access at any time.
#
# NOTE: If resources are protected by organization SAML enforcement, you must
# grant your personal access token access to this organization.
#
#   * Personal access tokens > Configure SSO > Authorize
#
# SEE ALSO:
#   * https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

# TODO: Test for organization SAML enforcement.
# TODO: Add option to write output to log file.

function usage {
  echo 'usage: git-clone-gh [-u, --user user] [-o, --org org] [-i identity_file] [access-token]'
  echo ''
  echo '  Arguments:'
  echo '    access-token: Personal access token'
  echo '      * The access token can be passed via a command-line argument or'
  echo '        set via the environment variable GITHUB_API_TOKEN.'
  echo ''
  echo '  Options:'
  echo "    -u, --user: Clone a user's repositories"
  echo "    -o, --org: Clone an organization's repositories"
  echo "    -i, --identity-file: File from which the identity (private key) for public key authentication is read."
}

args=("$@")

count=0
for arg in "${args[@]}"; do
  if [[ "${arg}" =~ ^\-.*|^\-\-.* ]]; then
    if [[ "${arg}" =~ ^\-u$|^\-\-user$ ]]; then
      user="${args[count+1]}"
    elif [[ "${arg}" =~ ^\-o$|^\-\-org$ ]]; then
      org="${args[count+1]}"
    elif [[ "${arg}" =~ ^\-i$|^\-\-identity\-file$ ]]; then
      identity_file="${args[count+1]}"
    else
      echo -en "\033[0;31m"
      echo "${arg} is not a valid option."
      echo -en "\033[0m\n"
      usage
      exit 1
    fi
  fi
  count=$((count+1))
done

# Error if 'user' and 'org' are either both set or not set.
if { [ -n "${user}" ] && [ -n "${org}" ]; } || { [ -z "${user}" ] && [ -z "${org}" ]; }; then
  echo -en "\033[0;31m"
  echo "ERROR: Specify either a user or organization."
  echo -en "\033[0m\n"
  usage
  exit 1
fi

# Check if 'identity_file' is set. If not, default to id_rsa.
if [ -z "${identity_file}" ]; then
  identity_file='id_rsa'
fi

# If there is an odd number of command-line arguments, the last argument is the
# GitHub access token.
if [ $(($# % 2)) == 1 ]; then
  access_token="${args[$#-1]}"
else
  # Check if the access token is set via the environment variable.
  access_token="${GITHUB_API_TOKEN}"
fi

if [ -z "${access_token}" ]; then
  echo -en "\033[0;31m"
  echo "ERROR: Specify a GitHub access token."
  echo -en "\033[0m\n"
  usage
  exit 1
fi

eval "$(ssh-agent -s)" >/dev/null 2>&1 && \
  ssh-add "${HOME}/.ssh/${identity_file}" >/dev/null 2>&1

trap 'ssh git@github.com >/dev/null 2>&1 || EXIT=$?' ERR

if [ "${EXIT}" == "255" ]; then
  echo -en "\033[0;31m"
  echo "Permission denied (publickey)."
  echo -en "\033[0m"
  exit 1
fi

# Set RESOURCE and check if GitHub user/organization exists.
if [ -n "${user}" ]; then
  RESOURCE="users/${user}/repos"
  if ! curl --fail --silent "https://api.github.com/users/${user}" >/dev/null ; then
    echo -en "\033[0;31m"
    echo "ERROR: GitHub user does not exist."
    echo -en "\033[0m\n"
    exit 1
  fi
elif [ -n "${org}" ]; then
  RESOURCE="orgs/${org}/repos"
  if ! curl --fail --silent "https://api.github.com/orgs/${org}" >/dev/null; then
    echo -en "\033[0;31m"
    echo "ERROR: GitHub organization does not exist."
    echo -en "\033[0m\n"
    exit 1
  fi
else
  exit 1
fi

# The GitHub API only returns 30 results. Therefore, increment PAGE until no
# results are returned.
PAGE=1
SSH_URLS=()
while true; do
  urls=($(curl -L --silent -X GET \
    --header "Authorization: Token ${access_token}" \
    "https://api.github.com/${RESOURCE}?sort=full_name&page=${PAGE}" | jq '.[].ssh_url' | tr -d \"))
  if [ ${#urls[@]} -eq 0 ]; then
    break
  else
    SSH_URLS+=("${urls[@]}")
  fi
  (( PAGE=PAGE+1 ))
done

for ssh_url in "${SSH_URLS[@]}"; do

  echo Cloning "${ssh_url}"...

  output=$(git clone "${ssh_url}" 2>&1)

  if [[ "${output}" =~ 'already exists' ]]; then
    echo -en "\033[0;31m"
    echo "Repository already exists."
    echo -en "\033[0m"
  elif [[ "${output}" =~ 'not found' ]]; then
    echo -en "\033[0;31m"
    echo "Please make sure you have the correct access rights and the repository exists."
    echo -en "\033[0m"
  fi

done

# Clean up ssh-agent
ssh-agent -k >/dev/null 2>&1
