#!/usr/bin/env bash
#
# DESCRIPTION
#   Set user.name, user.email, and remote host for each repository in the
#   current directory.
#
#   The remote host can be used in conjunction with an SSH configuration file
#   in order to manage multiple GitHub identities.
#
#     .ssh/config
#
#     # nickolaskraus-wf
#     Host workiva.github.com
#     HostName github.com
#     PreferredAuthentications publickey
#     IdentityFile ~/.ssh/id_rsa_workiva
#
# USAGE
#   git-config-all [USERNAME] [EMAIL] [HOST]
#
# ARGUMENTS
#   USERNAME    Username to set
#   EMAIL       User email to set
#   HOST        Remote Host to set
#
# OPTIONS
#   None
#
# EXAMPLES
#   git-config-all 'Nickolas Kraus' 'Nickolas.Kraus@workiva.com' 'workiva.github.com'

# Print usage information
function usage() {
  echo "usage: $0 [USERNAME] [EMAIL] [HOST]"
  echo ""
  echo "Arguments:"
  echo "  USERNAME    Username to set"
  echo "  EMAIL       User email to set"
  echo "  HOST        Remote Host to set"
  echo ""
}

if [ -z "${1}" ]; then
  echo -en "\033[0;31m"
  echo "Specify a user name."
  echo -en "\033[0m"
  usage
  exit 1
fi

if [ -z "${2}" ]; then
  echo -en "\033[0;31m"
  echo "Specify a user email."
  echo -en "\033[0m"
  usage
  exit 1
fi

if [ -z "${3}" ]; then
  echo -en "\033[0;31m"
  echo "Specify a remote host."
  echo -en "\033[0m"
  usage
  exit 1
fi

user_name="${1}"
user_email="${2}"
host="${3}"

for d in *; do \
  if [ -d "${d}" ]; then
    pushd "${d}" >/dev/null || exit
    git config user.name "${user_name}" && \
    git config user.email "${user_email}"
    orl_url="$(git remote get-url origin)"
    new_url=$(echo "${orl_url}" | gsed -E "s/@(.*):/@${host}:/")
    git remote set-url origin "${new_url}"
    popd >/dev/null || exit
  fi
done
