#!/usr/bin/env bash
#
# DESCRIPTION
#   Link Bash scripts to $HOME/bin.
#
#   Add the following to your shell configuration file:
#
#     export PATH=$HOME/bin:$PATH
#
#   Link executables to $HOME/bin:
#
#     ./install
#
# USAGE
#   install [OPTIONS]
#
# ARGUMENTS
#   None
#
# OPTIONS
#   -h, --help    Show this help message
#
# EXAMPLES
#   None

# Print usage information.
function usage() {
  echo "usage: install [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help    Show this help message"
  echo ""
}

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

mkdir -p "${HOME}"/bin

for f in "$(pwd)"/*; do
  # Skip if file a directory.
  [ -d "${f}" ] && continue
  # Skip if file not executable.
  [ ! -x "${f}" ] && continue
  # Skip if file is install script itself.
  [ "$(basename "${f}")" = "install" ] && continue
  ln -s "${f}" "${HOME}"/bin 2>/dev/null || true
done
