#!/usr/bin/env bash
#
# DESCRIPTION
#   Link Bash scripts to $HOME/bin.
#
#   Add the following to your shell configuration file:
#
#     export PATH=$HOME/bin:$PATH
#
#   Link executables to $HOME/bin:
#
#     ./install
#
# USAGE
#   install
#
# ARGUMENTS
#   None
#
# OPTIONS
#   None
#
# EXAMPLES
#   None

# Print usage information
function usage {
  echo "usage: $0"
}

mkdir -p "${HOME}"/bin

for f in "$(pwd)"/*; do
  [ ! -d "${f}" ] && [ -x "${f}" ] && [ "$(basename "${f}")" != "install" ] || continue
  ln -s "${f}" "${HOME}"/bin 2>/dev/null
done
