#!/usr/bin/env bash
#
# DESCRIPTION
#   Convert JSON to YAML.
#
# USAGE
#   json2yaml [FILE]
#
# ARGUMENTS
#   FILE    Path to JSON file
#
# OPTIONS
#   None
#
# EXAMPLES
#   None
function usage {
  echo 'usage: json2yaml [file]'
  echo ''
  echo '  Arguments:'
  echo '    file: JSON file to convert to YAML'
}

if [ -z "${1}" ]; then
  echo -en "\033[0;31m"
  echo -e "Must specify a file.\n"
  echo -en "\033[0m"
  usage
  exit 1
fi

file="${1}"

if [ ! -e "${file}" ]; then
  echo -en "\033[0;31m"
  echo "${file} does not exist."
  echo -en "\033[0m\n"
  exit 1
fi

FILENAME=$(echo "${file}" | cut -f 1 -d '.')

PYTHON=$(cat << END
import sys;
import json;
import yaml;

yaml.safe_dump(json.load(sys.stdin), sys.stdout, default_flow_style=False)

END
)

python -c "${PYTHON}" < "${FILENAME}.json" > "${FILENAME}.yaml"
