#!/bin/bash

file="$1"

if [ ! -e "$file" ]; then
  echo "'${file}' does not exist."
  exit
fi

filename=$(echo $file | cut -f 1 -d '.')

PYTHON=$(cat << END
import sys;
import json;
import yaml;

yaml.safe_dump(json.load(sys.stdin), sys.stdout, default_flow_style=False)

END
)

python -c "$PYTHON" < $filename.json > $filename.yaml
