#!/usr/bin/env bash
#
# DESCRIPTION
#   Remove trailing whitespace from every file in a given directory.
#   Excludes PNGs and files in .git/.
#
# USAGE
#   remove-whitespace [OPTIONS] [DIR]
#
# ARGUMENTS
#   DIR    Directory to use (optional, defaults to current directory)
#
# OPTIONS
#   -h, --help    Show this help message
#
# EXAMPLES
#   None

# Colors
red='\033[0;31m'
reset='\033[0m'

# Print usage information.
function usage() {
  echo "usage: remove-whitespace [OPTIONS] [DIR]"
  echo ""
  echo "Arguments:"
  echo "  DIR    Directory to use (optional, defaults to current directory)"
  echo ""
  echo "Options:"
  echo "  -h, --help    Show this help message"
  echo ""
}

dir=""

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
    *)
      dir="$1"
      shift
      break
      ;;
  esac
done

if [ -z "${dir}" ]; then
  dir="$(pwd)"
else
  if [ ! -e "${dir}" ]; then
    echo -e "${red}ERROR: ${dir} does not exist.${reset}" >&2
    exit 1
  fi
fi

if ! [ -x "$(command -v gsed)" ]; then
  echo -e "${red}ERROR: gsed is not installed.${reset}" >&2
  exit 1
fi

function remove_whitespace() {
  find . -type f \
    -name "*" \
    -not -name "*.png" \
    -not -path "./.git/*" \
    -not -path "./node_modules/*" \
    -exec gsed -i 's/[[:space:]]\+$//' {} \;
}

pushd "${dir}" >/dev/null || exit
remove_whitespace
popd >/dev/null || exit
