#!/usr/bin/env bash
#
# DESCRIPTION
#   Create a URL slug from a string.
#   The string to slugify is retrieved from the Clipboard.
#
# USAGE
#   slugify [OPTIONS]
#
# ARGUMENTS
#   None
#
# OPTIONS
#   -h, --help    Show this help message
#
# EXAMPLES
#   None

# Colors
red='\033[0;31m'
reset='\033[0m'

# Print usage information.
function usage() {
  echo "usage: slugify [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -h, --help    Show this help message"
  echo ""
}

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

if ! [ -x "$(command -v pbcopy)" ]; then
  echo -e "${red}ERROR: pbcopy is not installed.${reset}" >&2
  exit 1
fi

if ! [ -x "$(command -v pbpaste)" ]; then
  echo -e "${red}ERROR: pbpaste is not installed.${reset}" >&2
  exit 1
fi

# This command will do the following:
# 1. Convert whitespace to hyphens ('-')
# 2. Remove ',', ';', '/', '?', ':', '@', '=', '&' characters
# 3. Deduplicate hyphens ('--' >>> '-')
# 4. Change all characters to lowercase
# 5. Remove trailing newline ('\n')
pbpaste | \
  sed 's/[ ]/-/g' | \
  sed 's/[,;/?:@=&]//g' | \
  sed -E 's/[-]{2,}/-/g' | \
  awk '{print tolower($1)}' | \
  tr -d '\n' | \
  pbcopy
