#!/usr/bin/env bash

if ! [ -x "$(command -v pbcopy)"  ]; then
    echo 'Error: pbcopy is not installed.' >&2
    exit 1
fi

if ! [ -x "$(command -v pbpaste)"  ]; then
    echo 'Error: pbpaste is not installed.' >&2
    exit 1
fi

text=$(pbpaste | sed 's/[ ]/\-/g' | sed 's/[;/?:@=&]//g' | awk '{print tolower($1)}' | pbcopy)
