#!/usr/bin/env bash
#
# DESCRIPTION
#   Create a URL slug from a string.
#   The string to slugify is retrieved from the Clipboard.
#
# USAGE
#   slugify
#
# ARGUMENTS
#   None
#
# OPTIONS
#   None
#
# EXAMPLES
#   None

function usage {
  echo 'usage: slugify'
}

if ! [ -x "$(command -v pbcopy)"  ]; then
  echo 'Error: pbcopy is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v pbpaste)"  ]; then
  echo 'Error: pbpaste is not installed.' >&2
  exit 1
fi

# This command will do the following:
# 1. Convert whitespace to hyphens ('-')
# 2. Remove ',', ';', '/', '?', ':', '@', '=', '&' characters
# 3. Deduplicate hyphens ('--' >>> '-')
# 4. Change all characters to lowercase
# 5. Remove trailing newline ('\n')
pbpaste | sed 's/[ ]/\-/g' | sed 's/[,;/?:@=&]//g' | sed -E 's/[\-]{2,}/\-/g' | awk '{print tolower($1)}' | tr -d '\n' | pbcopy
