#!/usr/bin/env bash
#
# DESCRIPTION
#   Convert YAML to JSON.
#
# USAGE
#   yaml2json [OPTIONS] FILE
#
# ARGUMENTS
#   FILE    Path to YAML file
#
# OPTIONS
#   -h, --help    Show this help message
#
# EXAMPLES
#   None

# Colors
red='\033[0;31m'
reset='\033[0m'

# Print usage information.
function usage() {
  echo "usage: yaml2json [OPTIONS] FILE"
  echo ""
  echo "Arguments:"
  echo "  FILE    Path to YAML file"
  echo ""
  echo "Options:"
  echo "  -h, --help    Show this help message"
  echo ""
}

file=""

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    *) file="$1"; shift; break ;;
  esac
done

if [ -z "${file}" ]; then
  echo -e "${red}ERROR: Must specify a file.${reset}" >&2
  usage
  exit 1
fi

if [ ! -e "${file}" ]; then
  echo -e "${red}ERROR: ${file} does not exist.${reset}" >&2
  exit 1
fi

filename=$(echo "${file}" | cut -f 1 -d '.')

python_script=$(cat << END
import sys;
import json;
import yaml;

json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=2)

END
)

python -c "${python_script}" < "${file}" > "${filename}.json"
