#!/usr/bin/env bash
#
# DESCRIPTION
#   Convert YAML to JSON.
#
# USAGE
#   yaml2json [OPTIONS] FILE
#
# ARGUMENTS
#   FILE    Path to YAML file
#
# OPTIONS
#   -h, --help    Show this help message
#
# EXAMPLES
#   None

# Print usage information.
function usage() {
  echo "usage: $0 [OPTIONS] FILE"
  echo ""
  echo "Arguments:"
  echo "  FILE    Path to YAML file"
  echo ""
  echo "Options:"
  echo "  -h, --help    Show this help message"
  echo ""
}

file=""

# Parse command line arguments.
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; usage; exit 1 ;;
    *) file="$1"; shift; break ;;
  esac
done

if [ -z "${file}" ]; then
  echo -en "\033[0;31m"
  echo "ERROR: Must specify a file." >&2
  echo -en "\033[0m\n"
  usage
  exit 1
fi

if [ ! -e "${file}" ]; then
  echo -en "\033[0;31m"
  echo "${file} does not exist."
  echo -en "\033[0m\n"
  exit 1
fi

FILENAME=$(echo "${file}" | cut -f 1 -d '.')

PYTHON=$(cat << END
import sys;
import json;
import yaml;

json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=2)

END
)

python -c "${PYTHON}" < "${1}" > "${FILENAME}.json"
