#!/usr/bin/env bash
#
# DESCRIPTION
#   Convert YAML to JSON.
#
# USAGE
#   yaml2json [FILE]
#
# ARGUMENTS
#   FILE    Path to YAML file
#
# OPTIONS
#   None
#
# EXAMPLES
#   None

function usage {
  echo 'usage: yaml2json [file]'
  echo ''
  echo '  Arguments:'
  echo '    file: YAML file to convert to JSON'
}

if [ -z "${1}" ]; then
  echo -en "\033[0;31m"
  echo -e "Must specify a file.\n"
  echo -en "\033[0m"
  usage
  exit 1
fi

file="${1}"

if [ ! -e "${file}" ]; then
  echo -en "\033[0;31m"
  echo "${file} does not exist."
  echo -en "\033[0m\n"
  exit 1
fi

FILENAME=$(echo "${file}" | cut -f 1 -d '.')

PYTHON=$(cat << END
import sys;
import json;
import yaml;

json.dump(yaml.safe_load(sys.stdin), sys.stdout, indent=2)

END
)

python -c "${PYTHON}" < "${1}" > "${FILENAME}.json"
